//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.FabricDesign.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassType
    {
        public int ClassTypeId { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedbyUserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UPdatedbyUserId { get; set; }
        public System.DateTime UPdatedDate { get; set; }
    }
}
