//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.FabricDesign.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookUp
    {
        public int Id { get; set; }
        public int LookUpId { get; set; }
        public string Name { get; set; }
        public string Remarks { get; set; }
        public bool IsActive { get; set; }
        public string CreatedByUserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedByUserId { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
