//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.FabricDesign.edmx
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Fabric_DesignEntities1 : DbContext
    {
        public Fabric_DesignEntities1()
            : base("name=Fabric_DesignEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Buyer> Buyers { get; set; }
        public virtual DbSet<ClassType> ClassTypes { get; set; }
        public virtual DbSet<CountryCurrency> CountryCurrencies { get; set; }
        public virtual DbSet<FactoryList> FactoryLists { get; set; }
        public virtual DbSet<LookUp> LookUps { get; set; }
        public virtual DbSet<TypeCdDmt> TypeCdDmts { get; set; }
        public virtual DbSet<StyleMarchantXref> StyleMarchantXrefs { get; set; }
        public virtual DbSet<StyleMaterImage> StyleMaterImages { get; set; }
        public virtual DbSet<StateMaster> StateMasters { get; set; }
        public virtual DbSet<StyleMaster> StyleMasters { get; set; }
    
        public virtual ObjectResult<GetLookkupSP_Result> GetLookkupSP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLookkupSP_Result>("GetLookkupSP");
        }
    
        public virtual ObjectResult<GetStyleMaster_Result> GetStyleMaster()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStyleMaster_Result>("GetStyleMaster");
        }
    
        public virtual ObjectResult<GetTypecddmt_Result> GetTypecddmt()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTypecddmt_Result>("GetTypecddmt");
        }
    
        public virtual ObjectResult<SP_GetUsers_Result> SP_GetUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetUsers_Result>("SP_GetUsers");
        }
    
        public virtual ObjectResult<GetCountry_Result> GetCountry()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCountry_Result>("GetCountry");
        }
    
        public virtual ObjectResult<GetLookUp_Result> GetLookUp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLookUp_Result>("GetLookUp");
        }
    
        public virtual ObjectResult<GetCountrySP_Result> GetCountrySP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCountrySP_Result>("GetCountrySP");
        }
    
        public virtual ObjectResult<GetState_Result> GetState()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetState_Result>("GetState");
        }
    
        public virtual ObjectResult<GetBuyer_Result> GetBuyer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBuyer_Result>("GetBuyer");
        }
    
        public virtual ObjectResult<Getgarmenttypewithid_Result> Getgarmenttypewithid(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Getgarmenttypewithid_Result>("Getgarmenttypewithid", idParameter);
        }
    
        public virtual ObjectResult<GetOrdertypewithid_Result> GetOrdertypewithid(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrdertypewithid_Result>("GetOrdertypewithid", idParameter);
        }
    
        public virtual ObjectResult<Getseasonwithid_Result> Getseasonwithid(Nullable<int> lookUpId)
        {
            var lookUpIdParameter = lookUpId.HasValue ?
                new ObjectParameter("LookUpId", lookUpId) :
                new ObjectParameter("LookUpId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Getseasonwithid_Result>("Getseasonwithid", lookUpIdParameter);
        }
    
        public virtual ObjectResult<Garmentprocesswithid_Result> Garmentprocesswithid(Nullable<int> garmentprocessId)
        {
            var garmentprocessIdParameter = garmentprocessId.HasValue ?
                new ObjectParameter("GarmentprocessId", garmentprocessId) :
                new ObjectParameter("GarmentprocessId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Garmentprocesswithid_Result>("Garmentprocesswithid", garmentprocessIdParameter);
        }
    
        public virtual ObjectResult<GetSampletypewithid_Result> GetSampletypewithid(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSampletypewithid_Result>("GetSampletypewithid", idParameter);
        }
    
        public virtual ObjectResult<GetStyleMasterData_Result> GetStyleMasterData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStyleMasterData_Result>("GetStyleMasterData");
        }
    }
}
