//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.FabricDesign.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class StyleMaster
    {
        public int Id { get; set; }
        public string BuyerStyleNumber { get; set; }
        public string MarchantId { get; set; }
        public int BuyerId { get; set; }
        public int SeasonTypeId { get; set; }
        public int GarmentTypeId { get; set; }
        public Nullable<int> SampleTypeId { get; set; }
        public string TechPackName { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public string FileLocation { get; set; }
        public string FileExtension { get; set; }
        public Nullable<int> NumberofPcs { get; set; }
        public Nullable<System.DateTime> SampleSubmissionDate { get; set; }
        public Nullable<int> ExpectedOrderQty { get; set; }
        public Nullable<System.DateTime> ExpectedOrderDate { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> TechPackSampleReceivedDate { get; set; }
        public Nullable<int> OrderTypeId { get; set; }
        public Nullable<int> SamplingStatusId { get; set; }
        public string FabricManagerId { get; set; }
        public Nullable<int> GarmentProcessId { get; set; }
        public string CostingVersionId { get; set; }
        public Nullable<double> NoOfSamplesSentToBuyer { get; set; }
        public Nullable<double> NoOfSamplesPaidFor { get; set; }
        public Nullable<double> CostPerSample { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
