//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.FabricDesign.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeCdDmt
    {
        public int TypeCdId { get; set; }
        public Nullable<int> ClassTypeId { get; set; }
        public string Desc { get; set; }
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
